/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.drsmugleaf.eve.esi.api;

import com.github.drsmugleaf.eve.esi.ApiException;
import com.github.drsmugleaf.eve.esi.model.BadGateway;
import com.github.drsmugleaf.eve.esi.model.BadRequest;
import com.github.drsmugleaf.eve.esi.model.DeleteFleetsFleetIdMembersMemberIdNotFound;
import com.github.drsmugleaf.eve.esi.model.DeleteFleetsFleetIdSquadsSquadIdNotFound;
import com.github.drsmugleaf.eve.esi.model.DeleteFleetsFleetIdWingsWingIdNotFound;
import com.github.drsmugleaf.eve.esi.model.Forbidden;
import com.github.drsmugleaf.eve.esi.model.GetCharactersCharacterIdFleetNotFound;
import com.github.drsmugleaf.eve.esi.model.GetCharactersCharacterIdFleetOk;
import com.github.drsmugleaf.eve.esi.model.GetFleetsFleetIdMembers200Ok;
import com.github.drsmugleaf.eve.esi.model.GetFleetsFleetIdMembersNotFound;
import com.github.drsmugleaf.eve.esi.model.GetFleetsFleetIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetFleetsFleetIdOk;
import com.github.drsmugleaf.eve.esi.model.GetFleetsFleetIdWings200Ok;
import com.github.drsmugleaf.eve.esi.model.GetFleetsFleetIdWingsNotFound;
import com.github.drsmugleaf.eve.esi.model.InternalServerError;
import com.github.drsmugleaf.eve.esi.model.PostFleetsFleetIdMembersInvitation;
import com.github.drsmugleaf.eve.esi.model.PostFleetsFleetIdMembersNotFound;
import com.github.drsmugleaf.eve.esi.model.PostFleetsFleetIdMembersUnprocessableEntity;
import com.github.drsmugleaf.eve.esi.model.PostFleetsFleetIdWingsCreated;
import com.github.drsmugleaf.eve.esi.model.PostFleetsFleetIdWingsNotFound;
import com.github.drsmugleaf.eve.esi.model.PostFleetsFleetIdWingsWingIdSquadsCreated;
import com.github.drsmugleaf.eve.esi.model.PostFleetsFleetIdWingsWingIdSquadsNotFound;
import com.github.drsmugleaf.eve.esi.model.PutFleetsFleetIdMembersMemberIdMovement;
import com.github.drsmugleaf.eve.esi.model.PutFleetsFleetIdMembersMemberIdNotFound;
import com.github.drsmugleaf.eve.esi.model.PutFleetsFleetIdMembersMemberIdUnprocessableEntity;
import com.github.drsmugleaf.eve.esi.model.PutFleetsFleetIdNewSettings;
import com.github.drsmugleaf.eve.esi.model.PutFleetsFleetIdNotFound;
import com.github.drsmugleaf.eve.esi.model.PutFleetsFleetIdSquadsSquadIdNaming;
import com.github.drsmugleaf.eve.esi.model.PutFleetsFleetIdSquadsSquadIdNotFound;
import com.github.drsmugleaf.eve.esi.model.PutFleetsFleetIdWingsWingIdNaming;
import com.github.drsmugleaf.eve.esi.model.PutFleetsFleetIdWingsWingIdNotFound;
import com.github.drsmugleaf.eve.esi.model.ServiceUnavailable;
import com.github.drsmugleaf.eve.esi.model.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FleetsApi
 */
@Ignore
public class FleetsApiTest {

    private final FleetsApi api = new FleetsApi();

    
    /**
     * Kick fleet member
     *
     * Kick a fleet member  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/members/{member_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/members/{member_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/members/{member_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFleetsFleetIdMembersMemberIdTest() throws ApiException {
        Long fleetId = null;
        Integer memberId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.deleteFleetsFleetIdMembersMemberId(fleetId, memberId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Delete fleet squad
     *
     * Delete a fleet squad, only empty squads can be deleted  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/squads/{squad_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/squads/{squad_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/squads/{squad_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFleetsFleetIdSquadsSquadIdTest() throws ApiException {
        Long fleetId = null;
        Long squadId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.deleteFleetsFleetIdSquadsSquadId(fleetId, squadId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Delete fleet wing
     *
     * Delete a fleet wing, only empty wings can be deleted. The wing may contain squads, but the squads must be empty  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/{wing_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/{wing_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/{wing_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFleetsFleetIdWingsWingIdTest() throws ApiException {
        Long fleetId = null;
        Long wingId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.deleteFleetsFleetIdWingsWingId(fleetId, wingId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get character fleet info
     *
     * Return the fleet ID the character is in, if any.  --- Alternate route: &#x60;/dev/characters/{character_id}/fleet/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/fleet/&#x60;  Alternate route: &#x60;/v1/characters/{character_id}/fleet/&#x60;  --- This route is cached for up to 60 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdFleetTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        GetCharactersCharacterIdFleetOk response = api.getCharactersCharacterIdFleet(characterId, datasource, ifNoneMatch, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get fleet information
     *
     * Return details about a fleet  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/&#x60;  --- This route is cached for up to 5 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFleetsFleetIdTest() throws ApiException {
        Long fleetId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        GetFleetsFleetIdOk response = api.getFleetsFleetId(fleetId, datasource, ifNoneMatch, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get fleet members
     *
     * Return information about fleet members  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/members/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/members/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/members/&#x60;  --- This route is cached for up to 5 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFleetsFleetIdMembersTest() throws ApiException {
        Long fleetId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetFleetsFleetIdMembers200Ok> response = api.getFleetsFleetIdMembers(fleetId, datasource, ifNoneMatch, language, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get fleet wings
     *
     * Return information about wings in a fleet  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/&#x60;  --- This route is cached for up to 5 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFleetsFleetIdWingsTest() throws ApiException {
        Long fleetId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetFleetsFleetIdWings200Ok> response = api.getFleetsFleetIdWings(fleetId, datasource, ifNoneMatch, language, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Create fleet invitation
     *
     * Invite a character into the fleet. If a character has a CSPA charge set it is not possible to invite them to the fleet using ESI  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/members/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/members/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/members/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postFleetsFleetIdMembersTest() throws ApiException {
        Long fleetId = null;
        PostFleetsFleetIdMembersInvitation invitation = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.postFleetsFleetIdMembers(fleetId, invitation, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Create fleet wing
     *
     * Create a new wing in a fleet  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postFleetsFleetIdWingsTest() throws ApiException {
        Long fleetId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        PostFleetsFleetIdWingsCreated response = api.postFleetsFleetIdWings(fleetId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Create fleet squad
     *
     * Create a new squad in a fleet  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/{wing_id}/squads/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/{wing_id}/squads/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/{wing_id}/squads/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postFleetsFleetIdWingsWingIdSquadsTest() throws ApiException {
        Long fleetId = null;
        Long wingId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        PostFleetsFleetIdWingsWingIdSquadsCreated response = api.postFleetsFleetIdWingsWingIdSquads(fleetId, wingId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Update fleet
     *
     * Update settings about a fleet  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putFleetsFleetIdTest() throws ApiException {
        Long fleetId = null;
        PutFleetsFleetIdNewSettings newSettings = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.putFleetsFleetId(fleetId, newSettings, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Move fleet member
     *
     * Move a fleet member around  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/members/{member_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/members/{member_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/members/{member_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putFleetsFleetIdMembersMemberIdTest() throws ApiException {
        Long fleetId = null;
        Integer memberId = null;
        PutFleetsFleetIdMembersMemberIdMovement movement = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.putFleetsFleetIdMembersMemberId(fleetId, memberId, movement, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Rename fleet squad
     *
     * Rename a fleet squad  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/squads/{squad_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/squads/{squad_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/squads/{squad_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putFleetsFleetIdSquadsSquadIdTest() throws ApiException {
        Long fleetId = null;
        PutFleetsFleetIdSquadsSquadIdNaming naming = null;
        Long squadId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.putFleetsFleetIdSquadsSquadId(fleetId, naming, squadId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Rename fleet wing
     *
     * Rename a fleet wing  --- Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/{wing_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/{wing_id}/&#x60;  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/{wing_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putFleetsFleetIdWingsWingIdTest() throws ApiException {
        Long fleetId = null;
        PutFleetsFleetIdWingsWingIdNaming naming = null;
        Long wingId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.putFleetsFleetIdWingsWingId(fleetId, naming, wingId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
