/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.drsmugleaf.eve.esi.api;

import com.github.drsmugleaf.eve.esi.ApiException;
import com.github.drsmugleaf.eve.esi.model.BadGateway;
import com.github.drsmugleaf.eve.esi.model.BadRequest;
import com.github.drsmugleaf.eve.esi.model.Forbidden;
import com.github.drsmugleaf.eve.esi.model.GetCharactersCharacterIdKillmailsRecent200Ok;
import com.github.drsmugleaf.eve.esi.model.GetCorporationsCorporationIdKillmailsRecent200Ok;
import com.github.drsmugleaf.eve.esi.model.GetKillmailsKillmailIdKillmailHashOk;
import com.github.drsmugleaf.eve.esi.model.GetKillmailsKillmailIdKillmailHashUnprocessableEntity;
import com.github.drsmugleaf.eve.esi.model.InternalServerError;
import com.github.drsmugleaf.eve.esi.model.ServiceUnavailable;
import com.github.drsmugleaf.eve.esi.model.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for KillmailsApi
 */
@Ignore
public class KillmailsApiTest {

    private final KillmailsApi api = new KillmailsApi();

    
    /**
     * Get character kills and losses
     *
     * Return a list of character&#39;s recent kills and losses  --- Alternate route: &#x60;/dev/characters/{character_id}/killmails/recent/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/killmails/recent/&#x60;  Alternate route: &#x60;/v1/characters/{character_id}/killmails/recent/&#x60;  --- This route is cached for up to 120 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdKillmailsRecentTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer maxCount = null;
        Integer maxKillId = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdKillmailsRecent200Ok> response = api.getCharactersCharacterIdKillmailsRecent(characterId, datasource, ifNoneMatch, maxCount, maxKillId, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation kills and losses
     *
     * Get a list of corporation&#39;s recent kills and losses  --- Alternate route: &#x60;/dev/corporations/{corporation_id}/killmails/recent/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/killmails/recent/&#x60;  Alternate route: &#x60;/v1/corporations/{corporation_id}/killmails/recent/&#x60;  --- This route is cached for up to 300 seconds  --- Requires one of the following EVE corporation role(s): Director 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdKillmailsRecentTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer maxKillId = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdKillmailsRecent200Ok> response = api.getCorporationsCorporationIdKillmailsRecent(corporationId, datasource, ifNoneMatch, maxKillId, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get a single killmail
     *
     * Return a single killmail from its ID and hash  --- Alternate route: &#x60;/dev/killmails/{killmail_id}/{killmail_hash}/&#x60;  Alternate route: &#x60;/legacy/killmails/{killmail_id}/{killmail_hash}/&#x60;  Alternate route: &#x60;/v1/killmails/{killmail_id}/{killmail_hash}/&#x60;  --- This route is cached for up to 1209600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKillmailsKillmailIdKillmailHashTest() throws ApiException {
        String killmailHash = null;
        Integer killmailId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        GetKillmailsKillmailIdKillmailHashOk response = api.getKillmailsKillmailIdKillmailHash(killmailHash, killmailId, datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
