/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.drsmugleaf.eve.esi.api;

import com.github.drsmugleaf.eve.esi.ApiException;
import com.github.drsmugleaf.eve.esi.model.BadGateway;
import com.github.drsmugleaf.eve.esi.model.BadRequest;
import com.github.drsmugleaf.eve.esi.model.Forbidden;
import com.github.drsmugleaf.eve.esi.model.GetUniverseAncestries200Ok;
import com.github.drsmugleaf.eve.esi.model.GetUniverseAsteroidBeltsAsteroidBeltIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniverseAsteroidBeltsAsteroidBeltIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniverseBloodlines200Ok;
import com.github.drsmugleaf.eve.esi.model.GetUniverseCategoriesCategoryIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniverseCategoriesCategoryIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniverseConstellationsConstellationIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniverseConstellationsConstellationIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniverseFactions200Ok;
import com.github.drsmugleaf.eve.esi.model.GetUniverseGraphicsGraphicIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniverseGraphicsGraphicIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniverseGroupsGroupIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniverseGroupsGroupIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniverseMoonsMoonIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniverseMoonsMoonIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniversePlanetsPlanetIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniversePlanetsPlanetIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniverseRaces200Ok;
import com.github.drsmugleaf.eve.esi.model.GetUniverseRegionsRegionIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniverseRegionsRegionIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniverseStargatesStargateIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniverseStargatesStargateIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniverseStarsStarIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniverseStationsStationIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniverseStationsStationIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniverseStructuresStructureIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniverseStructuresStructureIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniverseSystemJumps200Ok;
import com.github.drsmugleaf.eve.esi.model.GetUniverseSystemKills200Ok;
import com.github.drsmugleaf.eve.esi.model.GetUniverseSystemsSystemIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniverseSystemsSystemIdOk;
import com.github.drsmugleaf.eve.esi.model.GetUniverseTypesTypeIdNotFound;
import com.github.drsmugleaf.eve.esi.model.GetUniverseTypesTypeIdOk;
import com.github.drsmugleaf.eve.esi.model.InternalServerError;
import com.github.drsmugleaf.eve.esi.model.PostUniverseIdsOk;
import com.github.drsmugleaf.eve.esi.model.PostUniverseNames200Ok;
import com.github.drsmugleaf.eve.esi.model.PostUniverseNamesNotFound;
import com.github.drsmugleaf.eve.esi.model.ServiceUnavailable;
import com.github.drsmugleaf.eve.esi.model.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UniverseApi
 */
@Ignore
public class UniverseApiTest {

    private final UniverseApi api = new UniverseApi();

    
    /**
     * Get ancestries
     *
     * Get all character ancestries  --- Alternate route: &#x60;/dev/universe/ancestries/&#x60;  Alternate route: &#x60;/legacy/universe/ancestries/&#x60;  Alternate route: &#x60;/v1/universe/ancestries/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseAncestriesTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetUniverseAncestries200Ok> response = api.getUniverseAncestries(datasource, ifNoneMatch, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get asteroid belt information
     *
     * Get information on an asteroid belt  --- Alternate route: &#x60;/dev/universe/asteroid_belts/{asteroid_belt_id}/&#x60;  Alternate route: &#x60;/legacy/universe/asteroid_belts/{asteroid_belt_id}/&#x60;  Alternate route: &#x60;/v1/universe/asteroid_belts/{asteroid_belt_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseAsteroidBeltsAsteroidBeltIdTest() throws ApiException {
        Integer asteroidBeltId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseAsteroidBeltsAsteroidBeltIdOk response = api.getUniverseAsteroidBeltsAsteroidBeltId(asteroidBeltId, datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get bloodlines
     *
     * Get a list of bloodlines  --- Alternate route: &#x60;/dev/universe/bloodlines/&#x60;  Alternate route: &#x60;/legacy/universe/bloodlines/&#x60;  Alternate route: &#x60;/v1/universe/bloodlines/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseBloodlinesTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetUniverseBloodlines200Ok> response = api.getUniverseBloodlines(datasource, ifNoneMatch, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get item categories
     *
     * Get a list of item categories  --- Alternate route: &#x60;/dev/universe/categories/&#x60;  Alternate route: &#x60;/legacy/universe/categories/&#x60;  Alternate route: &#x60;/v1/universe/categories/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseCategoriesTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseCategories(datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get item category information
     *
     * Get information of an item category  --- Alternate route: &#x60;/dev/universe/categories/{category_id}/&#x60;  Alternate route: &#x60;/legacy/universe/categories/{category_id}/&#x60;  Alternate route: &#x60;/v1/universe/categories/{category_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseCategoriesCategoryIdTest() throws ApiException {
        Integer categoryId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseCategoriesCategoryIdOk response = api.getUniverseCategoriesCategoryId(categoryId, datasource, ifNoneMatch, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get constellations
     *
     * Get a list of constellations  --- Alternate route: &#x60;/dev/universe/constellations/&#x60;  Alternate route: &#x60;/legacy/universe/constellations/&#x60;  Alternate route: &#x60;/v1/universe/constellations/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseConstellationsTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseConstellations(datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get constellation information
     *
     * Get information on a constellation  --- Alternate route: &#x60;/dev/universe/constellations/{constellation_id}/&#x60;  Alternate route: &#x60;/legacy/universe/constellations/{constellation_id}/&#x60;  Alternate route: &#x60;/v1/universe/constellations/{constellation_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseConstellationsConstellationIdTest() throws ApiException {
        Integer constellationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseConstellationsConstellationIdOk response = api.getUniverseConstellationsConstellationId(constellationId, datasource, ifNoneMatch, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get factions
     *
     * Get a list of factions  --- Alternate route: &#x60;/dev/universe/factions/&#x60;  Alternate route: &#x60;/v2/universe/factions/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseFactionsTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetUniverseFactions200Ok> response = api.getUniverseFactions(datasource, ifNoneMatch, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get graphics
     *
     * Get a list of graphics  --- Alternate route: &#x60;/dev/universe/graphics/&#x60;  Alternate route: &#x60;/legacy/universe/graphics/&#x60;  Alternate route: &#x60;/v1/universe/graphics/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseGraphicsTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseGraphics(datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get graphic information
     *
     * Get information on a graphic  --- Alternate route: &#x60;/dev/universe/graphics/{graphic_id}/&#x60;  Alternate route: &#x60;/legacy/universe/graphics/{graphic_id}/&#x60;  Alternate route: &#x60;/v1/universe/graphics/{graphic_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseGraphicsGraphicIdTest() throws ApiException {
        Integer graphicId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseGraphicsGraphicIdOk response = api.getUniverseGraphicsGraphicId(graphicId, datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get item groups
     *
     * Get a list of item groups  --- Alternate route: &#x60;/dev/universe/groups/&#x60;  Alternate route: &#x60;/legacy/universe/groups/&#x60;  Alternate route: &#x60;/v1/universe/groups/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseGroupsTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseGroups(datasource, ifNoneMatch, page, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get item group information
     *
     * Get information on an item group  --- Alternate route: &#x60;/dev/universe/groups/{group_id}/&#x60;  Alternate route: &#x60;/legacy/universe/groups/{group_id}/&#x60;  Alternate route: &#x60;/v1/universe/groups/{group_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseGroupsGroupIdTest() throws ApiException {
        Integer groupId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseGroupsGroupIdOk response = api.getUniverseGroupsGroupId(groupId, datasource, ifNoneMatch, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get moon information
     *
     * Get information on a moon  --- Alternate route: &#x60;/dev/universe/moons/{moon_id}/&#x60;  Alternate route: &#x60;/legacy/universe/moons/{moon_id}/&#x60;  Alternate route: &#x60;/v1/universe/moons/{moon_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseMoonsMoonIdTest() throws ApiException {
        Integer moonId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseMoonsMoonIdOk response = api.getUniverseMoonsMoonId(moonId, datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get planet information
     *
     * Get information on a planet  --- Alternate route: &#x60;/dev/universe/planets/{planet_id}/&#x60;  Alternate route: &#x60;/legacy/universe/planets/{planet_id}/&#x60;  Alternate route: &#x60;/v1/universe/planets/{planet_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniversePlanetsPlanetIdTest() throws ApiException {
        Integer planetId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniversePlanetsPlanetIdOk response = api.getUniversePlanetsPlanetId(planetId, datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get character races
     *
     * Get a list of character races  --- Alternate route: &#x60;/dev/universe/races/&#x60;  Alternate route: &#x60;/legacy/universe/races/&#x60;  Alternate route: &#x60;/v1/universe/races/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseRacesTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetUniverseRaces200Ok> response = api.getUniverseRaces(datasource, ifNoneMatch, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get regions
     *
     * Get a list of regions  --- Alternate route: &#x60;/dev/universe/regions/&#x60;  Alternate route: &#x60;/legacy/universe/regions/&#x60;  Alternate route: &#x60;/v1/universe/regions/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseRegionsTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseRegions(datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get region information
     *
     * Get information on a region  --- Alternate route: &#x60;/dev/universe/regions/{region_id}/&#x60;  Alternate route: &#x60;/legacy/universe/regions/{region_id}/&#x60;  Alternate route: &#x60;/v1/universe/regions/{region_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseRegionsRegionIdTest() throws ApiException {
        Integer regionId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseRegionsRegionIdOk response = api.getUniverseRegionsRegionId(regionId, datasource, ifNoneMatch, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get stargate information
     *
     * Get information on a stargate  --- Alternate route: &#x60;/dev/universe/stargates/{stargate_id}/&#x60;  Alternate route: &#x60;/legacy/universe/stargates/{stargate_id}/&#x60;  Alternate route: &#x60;/v1/universe/stargates/{stargate_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseStargatesStargateIdTest() throws ApiException {
        Integer stargateId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseStargatesStargateIdOk response = api.getUniverseStargatesStargateId(stargateId, datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get star information
     *
     * Get information on a star  --- Alternate route: &#x60;/dev/universe/stars/{star_id}/&#x60;  Alternate route: &#x60;/legacy/universe/stars/{star_id}/&#x60;  Alternate route: &#x60;/v1/universe/stars/{star_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseStarsStarIdTest() throws ApiException {
        Integer starId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseStarsStarIdOk response = api.getUniverseStarsStarId(starId, datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get station information
     *
     * Get information on a station  --- Alternate route: &#x60;/dev/universe/stations/{station_id}/&#x60;  Alternate route: &#x60;/v2/universe/stations/{station_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseStationsStationIdTest() throws ApiException {
        Integer stationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseStationsStationIdOk response = api.getUniverseStationsStationId(stationId, datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * List all public structures
     *
     * List all public structures  --- Alternate route: &#x60;/dev/universe/structures/&#x60;  Alternate route: &#x60;/legacy/universe/structures/&#x60;  Alternate route: &#x60;/v1/universe/structures/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseStructuresTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Long> response = api.getUniverseStructures(datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get structure information
     *
     * Returns information on requested structure, if you are on the ACL. Otherwise, returns \&quot;Forbidden\&quot; for all inputs.  --- Alternate route: &#x60;/dev/universe/structures/{structure_id}/&#x60;  Alternate route: &#x60;/legacy/universe/structures/{structure_id}/&#x60;  Alternate route: &#x60;/v1/universe/structures/{structure_id}/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseStructuresStructureIdTest() throws ApiException {
        Long structureId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseStructuresStructureIdOk response = api.getUniverseStructuresStructureId(structureId, datasource, ifNoneMatch, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get system jumps
     *
     * Get the number of jumps in solar systems within the last hour ending at the timestamp of the Last-Modified header, excluding wormhole space. Only systems with jumps will be listed  --- Alternate route: &#x60;/dev/universe/system_jumps/&#x60;  Alternate route: &#x60;/legacy/universe/system_jumps/&#x60;  Alternate route: &#x60;/v1/universe/system_jumps/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseSystemJumpsTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetUniverseSystemJumps200Ok> response = api.getUniverseSystemJumps(datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get system kills
     *
     * Get the number of ship, pod and NPC kills per solar system within the last hour ending at the timestamp of the Last-Modified header, excluding wormhole space. Only systems with kills will be listed  --- Alternate route: &#x60;/dev/universe/system_kills/&#x60;  Alternate route: &#x60;/v2/universe/system_kills/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseSystemKillsTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetUniverseSystemKills200Ok> response = api.getUniverseSystemKills(datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get solar systems
     *
     * Get a list of solar systems  --- Alternate route: &#x60;/dev/universe/systems/&#x60;  Alternate route: &#x60;/legacy/universe/systems/&#x60;  Alternate route: &#x60;/v1/universe/systems/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseSystemsTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseSystems(datasource, ifNoneMatch, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get solar system information
     *
     * Get information on a solar system  --- Alternate route: &#x60;/dev/universe/systems/{system_id}/&#x60;  Alternate route: &#x60;/v3/universe/systems/{system_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseSystemsSystemIdTest() throws ApiException {
        Integer systemId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseSystemsSystemIdOk response = api.getUniverseSystemsSystemId(systemId, datasource, ifNoneMatch, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get types
     *
     * Get a list of type ids  --- Alternate route: &#x60;/dev/universe/types/&#x60;  Alternate route: &#x60;/legacy/universe/types/&#x60;  Alternate route: &#x60;/v1/universe/types/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseTypesTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseTypes(datasource, ifNoneMatch, page, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get type information
     *
     * Get information on a type  --- Alternate route: &#x60;/dev/universe/types/{type_id}/&#x60;  Alternate route: &#x60;/v3/universe/types/{type_id}/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseTypesTypeIdTest() throws ApiException {
        Integer typeId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseTypesTypeIdOk response = api.getUniverseTypesTypeId(typeId, datasource, ifNoneMatch, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Bulk names to IDs
     *
     * Resolve a set of names to IDs in the following categories: agents, alliances, characters, constellations, corporations factions, inventory_types, regions, stations, and systems. Only exact matches will be returned. All names searched for are cached for 12 hours.  --- Alternate route: &#x60;/dev/universe/ids/&#x60;  Alternate route: &#x60;/legacy/universe/ids/&#x60;  Alternate route: &#x60;/v1/universe/ids/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUniverseIdsTest() throws ApiException {
        List<String> names = null;
        String datasource = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        PostUniverseIdsOk response = api.postUniverseIds(names, datasource, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get names and categories for a set of ID&#39;s
     *
     * Resolve a set of IDs to names and categories. Supported ID&#39;s for resolving are: Characters, Corporations, Alliances, Stations, Solar Systems, Constellations, Regions, Types.  --- Alternate route: &#x60;/dev/universe/names/&#x60;  Alternate route: &#x60;/v2/universe/names/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUniverseNamesTest() throws ApiException {
        List<Integer> ids = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<PostUniverseNames200Ok> response = api.postUniverseNames(ids, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
